/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddressVerificationDetailSignatureDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressVerificationDetailSignatureDetail{}

// AddressVerificationDetailSignatureDetail Off-chain signature provenance. Present only when `verification_method=SIGNATURE`. 
type AddressVerificationDetailSignatureDetail struct {
	// The self-custody wallet address that signed the challenge.
	Address string `json:"address"`
	// The challenge string that was signed.
	Challenge NullableString `json:"challenge,omitempty"`
	// The wallet signature submitted by the client.
	Signature NullableString `json:"signature,omitempty"`
	// Timestamp (milliseconds) when the signature was verified.
	VerifiedAt NullableInt64 `json:"verified_at,omitempty"`
}

type _AddressVerificationDetailSignatureDetail AddressVerificationDetailSignatureDetail

// NewAddressVerificationDetailSignatureDetail instantiates a new AddressVerificationDetailSignatureDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressVerificationDetailSignatureDetail(address string) *AddressVerificationDetailSignatureDetail {
	this := AddressVerificationDetailSignatureDetail{}
	this.Address = address
	return &this
}

// NewAddressVerificationDetailSignatureDetailWithDefaults instantiates a new AddressVerificationDetailSignatureDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressVerificationDetailSignatureDetailWithDefaults() *AddressVerificationDetailSignatureDetail {
	this := AddressVerificationDetailSignatureDetail{}
	return &this
}

// GetAddress returns the Address field value
func (o *AddressVerificationDetailSignatureDetail) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetailSignatureDetail) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *AddressVerificationDetailSignatureDetail) SetAddress(v string) {
	o.Address = v
}

// GetChallenge returns the Challenge field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressVerificationDetailSignatureDetail) GetChallenge() string {
	if o == nil || IsNil(o.Challenge.Get()) {
		var ret string
		return ret
	}
	return *o.Challenge.Get()
}

// GetChallengeOk returns a tuple with the Challenge field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressVerificationDetailSignatureDetail) GetChallengeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Challenge.Get(), o.Challenge.IsSet()
}

// HasChallenge returns a boolean if a field has been set.
func (o *AddressVerificationDetailSignatureDetail) HasChallenge() bool {
	if o != nil && o.Challenge.IsSet() {
		return true
	}

	return false
}

// SetChallenge gets a reference to the given NullableString and assigns it to the Challenge field.
func (o *AddressVerificationDetailSignatureDetail) SetChallenge(v string) {
	o.Challenge.Set(&v)
}
// SetChallengeNil sets the value for Challenge to be an explicit nil
func (o *AddressVerificationDetailSignatureDetail) SetChallengeNil() {
	o.Challenge.Set(nil)
}

// UnsetChallenge ensures that no value is present for Challenge, not even an explicit nil
func (o *AddressVerificationDetailSignatureDetail) UnsetChallenge() {
	o.Challenge.Unset()
}

// GetSignature returns the Signature field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressVerificationDetailSignatureDetail) GetSignature() string {
	if o == nil || IsNil(o.Signature.Get()) {
		var ret string
		return ret
	}
	return *o.Signature.Get()
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressVerificationDetailSignatureDetail) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Signature.Get(), o.Signature.IsSet()
}

// HasSignature returns a boolean if a field has been set.
func (o *AddressVerificationDetailSignatureDetail) HasSignature() bool {
	if o != nil && o.Signature.IsSet() {
		return true
	}

	return false
}

// SetSignature gets a reference to the given NullableString and assigns it to the Signature field.
func (o *AddressVerificationDetailSignatureDetail) SetSignature(v string) {
	o.Signature.Set(&v)
}
// SetSignatureNil sets the value for Signature to be an explicit nil
func (o *AddressVerificationDetailSignatureDetail) SetSignatureNil() {
	o.Signature.Set(nil)
}

// UnsetSignature ensures that no value is present for Signature, not even an explicit nil
func (o *AddressVerificationDetailSignatureDetail) UnsetSignature() {
	o.Signature.Unset()
}

// GetVerifiedAt returns the VerifiedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressVerificationDetailSignatureDetail) GetVerifiedAt() int64 {
	if o == nil || IsNil(o.VerifiedAt.Get()) {
		var ret int64
		return ret
	}
	return *o.VerifiedAt.Get()
}

// GetVerifiedAtOk returns a tuple with the VerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressVerificationDetailSignatureDetail) GetVerifiedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.VerifiedAt.Get(), o.VerifiedAt.IsSet()
}

// HasVerifiedAt returns a boolean if a field has been set.
func (o *AddressVerificationDetailSignatureDetail) HasVerifiedAt() bool {
	if o != nil && o.VerifiedAt.IsSet() {
		return true
	}

	return false
}

// SetVerifiedAt gets a reference to the given NullableInt64 and assigns it to the VerifiedAt field.
func (o *AddressVerificationDetailSignatureDetail) SetVerifiedAt(v int64) {
	o.VerifiedAt.Set(&v)
}
// SetVerifiedAtNil sets the value for VerifiedAt to be an explicit nil
func (o *AddressVerificationDetailSignatureDetail) SetVerifiedAtNil() {
	o.VerifiedAt.Set(nil)
}

// UnsetVerifiedAt ensures that no value is present for VerifiedAt, not even an explicit nil
func (o *AddressVerificationDetailSignatureDetail) UnsetVerifiedAt() {
	o.VerifiedAt.Unset()
}

func (o AddressVerificationDetailSignatureDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressVerificationDetailSignatureDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	if o.Challenge.IsSet() {
		toSerialize["challenge"] = o.Challenge.Get()
	}
	if o.Signature.IsSet() {
		toSerialize["signature"] = o.Signature.Get()
	}
	if o.VerifiedAt.IsSet() {
		toSerialize["verified_at"] = o.VerifiedAt.Get()
	}
	return toSerialize, nil
}

func (o *AddressVerificationDetailSignatureDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddressVerificationDetailSignatureDetail := _AddressVerificationDetailSignatureDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddressVerificationDetailSignatureDetail)

	if err != nil {
		return err
	}

	*o = AddressVerificationDetailSignatureDetail(varAddressVerificationDetailSignatureDetail)

	return err
}

type NullableAddressVerificationDetailSignatureDetail struct {
	value *AddressVerificationDetailSignatureDetail
	isSet bool
}

func (v NullableAddressVerificationDetailSignatureDetail) Get() *AddressVerificationDetailSignatureDetail {
	return v.value
}

func (v *NullableAddressVerificationDetailSignatureDetail) Set(val *AddressVerificationDetailSignatureDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressVerificationDetailSignatureDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressVerificationDetailSignatureDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressVerificationDetailSignatureDetail(val *AddressVerificationDetailSignatureDetail) *NullableAddressVerificationDetailSignatureDetail {
	return &NullableAddressVerificationDetailSignatureDetail{value: val, isSet: true}
}

func (v NullableAddressVerificationDetailSignatureDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressVerificationDetailSignatureDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


