/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSatoshiTestChallengeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSatoshiTestChallengeRequest{}

// CreateSatoshiTestChallengeRequest Request body for creating a Satoshi Test challenge. A single endpoint covers both the two-step flow (`PREPARE` then `SUBMIT`) and the one-shot flow (`SUBMIT` directly). Idempotent on `(chain_id, from_address)` per organization. 
type CreateSatoshiTestChallengeRequest struct {
	Action SatoshiTestChallengeAction `json:"action"`
	// The chain ID of the counterparty address. See the operation description for supported chains.
	ChainId string `json:"chain_id"`
	// The counterparty (self-custody) wallet address that will transfer the micro-deposit.
	FromAddress string `json:"from_address"`
	// The Cobo transaction ID that this Satoshi Test is verifying for.
	TransactionId string `json:"transaction_id"`
	TransactionType TravelRuleTransactionType `json:"transaction_type"`
	// The `challenge_id` returned by a previous `PREPARE` call. - When `action=SUBMIT`: if provided, activates that specific challenge by id (recommended when you cached the id client-side after `PREPARE`). If omitted, the server activates the latest matching challenge identified by `(chain_id, from_address)`. - When `action=PREPARE`: **must be omitted**. A new challenge is always generated; passing a `challenge_id` here will cause the request to be rejected. 
	ChallengeId *string `json:"challenge_id,omitempty"`
}

type _CreateSatoshiTestChallengeRequest CreateSatoshiTestChallengeRequest

// NewCreateSatoshiTestChallengeRequest instantiates a new CreateSatoshiTestChallengeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSatoshiTestChallengeRequest(action SatoshiTestChallengeAction, chainId string, fromAddress string, transactionId string, transactionType TravelRuleTransactionType) *CreateSatoshiTestChallengeRequest {
	this := CreateSatoshiTestChallengeRequest{}
	this.Action = action
	this.ChainId = chainId
	this.FromAddress = fromAddress
	this.TransactionId = transactionId
	this.TransactionType = transactionType
	return &this
}

// NewCreateSatoshiTestChallengeRequestWithDefaults instantiates a new CreateSatoshiTestChallengeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSatoshiTestChallengeRequestWithDefaults() *CreateSatoshiTestChallengeRequest {
	this := CreateSatoshiTestChallengeRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *CreateSatoshiTestChallengeRequest) GetAction() SatoshiTestChallengeAction {
	if o == nil {
		var ret SatoshiTestChallengeAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *CreateSatoshiTestChallengeRequest) GetActionOk() (*SatoshiTestChallengeAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *CreateSatoshiTestChallengeRequest) SetAction(v SatoshiTestChallengeAction) {
	o.Action = v
}

// GetChainId returns the ChainId field value
func (o *CreateSatoshiTestChallengeRequest) GetChainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *CreateSatoshiTestChallengeRequest) GetChainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *CreateSatoshiTestChallengeRequest) SetChainId(v string) {
	o.ChainId = v
}

// GetFromAddress returns the FromAddress field value
func (o *CreateSatoshiTestChallengeRequest) GetFromAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromAddress
}

// GetFromAddressOk returns a tuple with the FromAddress field value
// and a boolean to check if the value has been set.
func (o *CreateSatoshiTestChallengeRequest) GetFromAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromAddress, true
}

// SetFromAddress sets field value
func (o *CreateSatoshiTestChallengeRequest) SetFromAddress(v string) {
	o.FromAddress = v
}

// GetTransactionId returns the TransactionId field value
func (o *CreateSatoshiTestChallengeRequest) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *CreateSatoshiTestChallengeRequest) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *CreateSatoshiTestChallengeRequest) SetTransactionId(v string) {
	o.TransactionId = v
}

// GetTransactionType returns the TransactionType field value
func (o *CreateSatoshiTestChallengeRequest) GetTransactionType() TravelRuleTransactionType {
	if o == nil {
		var ret TravelRuleTransactionType
		return ret
	}

	return o.TransactionType
}

// GetTransactionTypeOk returns a tuple with the TransactionType field value
// and a boolean to check if the value has been set.
func (o *CreateSatoshiTestChallengeRequest) GetTransactionTypeOk() (*TravelRuleTransactionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionType, true
}

// SetTransactionType sets field value
func (o *CreateSatoshiTestChallengeRequest) SetTransactionType(v TravelRuleTransactionType) {
	o.TransactionType = v
}

// GetChallengeId returns the ChallengeId field value if set, zero value otherwise.
func (o *CreateSatoshiTestChallengeRequest) GetChallengeId() string {
	if o == nil || IsNil(o.ChallengeId) {
		var ret string
		return ret
	}
	return *o.ChallengeId
}

// GetChallengeIdOk returns a tuple with the ChallengeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSatoshiTestChallengeRequest) GetChallengeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChallengeId) {
		return nil, false
	}
	return o.ChallengeId, true
}

// HasChallengeId returns a boolean if a field has been set.
func (o *CreateSatoshiTestChallengeRequest) HasChallengeId() bool {
	if o != nil && !IsNil(o.ChallengeId) {
		return true
	}

	return false
}

// SetChallengeId gets a reference to the given string and assigns it to the ChallengeId field.
func (o *CreateSatoshiTestChallengeRequest) SetChallengeId(v string) {
	o.ChallengeId = &v
}

func (o CreateSatoshiTestChallengeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSatoshiTestChallengeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["chain_id"] = o.ChainId
	toSerialize["from_address"] = o.FromAddress
	toSerialize["transaction_id"] = o.TransactionId
	toSerialize["transaction_type"] = o.TransactionType
	if !IsNil(o.ChallengeId) {
		toSerialize["challenge_id"] = o.ChallengeId
	}
	return toSerialize, nil
}

func (o *CreateSatoshiTestChallengeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"chain_id",
		"from_address",
		"transaction_id",
		"transaction_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSatoshiTestChallengeRequest := _CreateSatoshiTestChallengeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSatoshiTestChallengeRequest)

	if err != nil {
		return err
	}

	*o = CreateSatoshiTestChallengeRequest(varCreateSatoshiTestChallengeRequest)

	return err
}

type NullableCreateSatoshiTestChallengeRequest struct {
	value *CreateSatoshiTestChallengeRequest
	isSet bool
}

func (v NullableCreateSatoshiTestChallengeRequest) Get() *CreateSatoshiTestChallengeRequest {
	return v.value
}

func (v *NullableCreateSatoshiTestChallengeRequest) Set(val *CreateSatoshiTestChallengeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSatoshiTestChallengeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSatoshiTestChallengeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSatoshiTestChallengeRequest(val *CreateSatoshiTestChallengeRequest) *NullableCreateSatoshiTestChallengeRequest {
	return &NullableCreateSatoshiTestChallengeRequest{value: val, isSet: true}
}

func (v NullableCreateSatoshiTestChallengeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSatoshiTestChallengeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


