/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignatureChallenge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignatureChallenge{}

// SignatureChallenge A signature challenge for self-custody wallet verification. The wallet owner must sign the `challenge` string with the wallet associated with `address` and submit the signature via [Submit Travel Rule information for deposits](#operation/submit_deposit_travel_rule_info) or [withdrawals](#operation/submit_withdraw_travel_rule_info). The challenge is time-bounded — each call rotates the challenge and only the most recently-issued value will verify. 
type SignatureChallenge struct {
	// The self-custody wallet address that must sign this challenge. This is the counterparty address for the transaction: for deposits it is the sender's wallet, and for withdrawals it is the recipient's wallet. 
	Address string `json:"address"`
	// The human-readable, time-sensitive message to sign. Contains the wallet address, a unique nonce, and a timestamp. 
	Challenge string `json:"challenge"`
	// Number of seconds before the challenge expires. The signature must be submitted within this window.
	ExpiresIn int32 `json:"expires_in"`
}

type _SignatureChallenge SignatureChallenge

// NewSignatureChallenge instantiates a new SignatureChallenge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignatureChallenge(address string, challenge string, expiresIn int32) *SignatureChallenge {
	this := SignatureChallenge{}
	this.Address = address
	this.Challenge = challenge
	this.ExpiresIn = expiresIn
	return &this
}

// NewSignatureChallengeWithDefaults instantiates a new SignatureChallenge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignatureChallengeWithDefaults() *SignatureChallenge {
	this := SignatureChallenge{}
	return &this
}

// GetAddress returns the Address field value
func (o *SignatureChallenge) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *SignatureChallenge) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *SignatureChallenge) SetAddress(v string) {
	o.Address = v
}

// GetChallenge returns the Challenge field value
func (o *SignatureChallenge) GetChallenge() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Challenge
}

// GetChallengeOk returns a tuple with the Challenge field value
// and a boolean to check if the value has been set.
func (o *SignatureChallenge) GetChallengeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Challenge, true
}

// SetChallenge sets field value
func (o *SignatureChallenge) SetChallenge(v string) {
	o.Challenge = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *SignatureChallenge) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *SignatureChallenge) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *SignatureChallenge) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

func (o SignatureChallenge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignatureChallenge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["challenge"] = o.Challenge
	toSerialize["expires_in"] = o.ExpiresIn
	return toSerialize, nil
}

func (o *SignatureChallenge) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"challenge",
		"expires_in",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignatureChallenge := _SignatureChallenge{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignatureChallenge)

	if err != nil {
		return err
	}

	*o = SignatureChallenge(varSignatureChallenge)

	return err
}

type NullableSignatureChallenge struct {
	value *SignatureChallenge
	isSet bool
}

func (v NullableSignatureChallenge) Get() *SignatureChallenge {
	return v.value
}

func (v *NullableSignatureChallenge) Set(val *SignatureChallenge) {
	v.value = val
	v.isSet = true
}

func (v NullableSignatureChallenge) IsSet() bool {
	return v.isSet
}

func (v *NullableSignatureChallenge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignatureChallenge(val *SignatureChallenge) *NullableSignatureChallenge {
	return &NullableSignatureChallenge{value: val, isSet: true}
}

func (v NullableSignatureChallenge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignatureChallenge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


