/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CancelSatoshiTestChallengeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelSatoshiTestChallengeRequest{}

// CancelSatoshiTestChallengeRequest Request body for cancelling a Satoshi Test challenge that is in `PREPARE` or `PENDING` status.
type CancelSatoshiTestChallengeRequest struct {
	// The challenge ID to cancel.
	ChallengeId string `json:"challenge_id"`
}

type _CancelSatoshiTestChallengeRequest CancelSatoshiTestChallengeRequest

// NewCancelSatoshiTestChallengeRequest instantiates a new CancelSatoshiTestChallengeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelSatoshiTestChallengeRequest(challengeId string) *CancelSatoshiTestChallengeRequest {
	this := CancelSatoshiTestChallengeRequest{}
	this.ChallengeId = challengeId
	return &this
}

// NewCancelSatoshiTestChallengeRequestWithDefaults instantiates a new CancelSatoshiTestChallengeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelSatoshiTestChallengeRequestWithDefaults() *CancelSatoshiTestChallengeRequest {
	this := CancelSatoshiTestChallengeRequest{}
	return &this
}

// GetChallengeId returns the ChallengeId field value
func (o *CancelSatoshiTestChallengeRequest) GetChallengeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChallengeId
}

// GetChallengeIdOk returns a tuple with the ChallengeId field value
// and a boolean to check if the value has been set.
func (o *CancelSatoshiTestChallengeRequest) GetChallengeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChallengeId, true
}

// SetChallengeId sets field value
func (o *CancelSatoshiTestChallengeRequest) SetChallengeId(v string) {
	o.ChallengeId = v
}

func (o CancelSatoshiTestChallengeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelSatoshiTestChallengeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["challenge_id"] = o.ChallengeId
	return toSerialize, nil
}

func (o *CancelSatoshiTestChallengeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"challenge_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelSatoshiTestChallengeRequest := _CancelSatoshiTestChallengeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCancelSatoshiTestChallengeRequest)

	if err != nil {
		return err
	}

	*o = CancelSatoshiTestChallengeRequest(varCancelSatoshiTestChallengeRequest)

	return err
}

type NullableCancelSatoshiTestChallengeRequest struct {
	value *CancelSatoshiTestChallengeRequest
	isSet bool
}

func (v NullableCancelSatoshiTestChallengeRequest) Get() *CancelSatoshiTestChallengeRequest {
	return v.value
}

func (v *NullableCancelSatoshiTestChallengeRequest) Set(val *CancelSatoshiTestChallengeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelSatoshiTestChallengeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelSatoshiTestChallengeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelSatoshiTestChallengeRequest(val *CancelSatoshiTestChallengeRequest) *NullableCancelSatoshiTestChallengeRequest {
	return &NullableCancelSatoshiTestChallengeRequest{value: val, isSet: true}
}

func (v NullableCancelSatoshiTestChallengeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelSatoshiTestChallengeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


