/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"fmt"
)

// SatoshiTestChallengeStatus The lifecycle status of a Satoshi Test challenge. - `PREPARE`: Challenge created (address and amount returned); the 180-minute countdown is not started yet. - `PENDING`: Challenge submitted; countdown active, waiting for the counterparty's on-chain transfer. - `MATCHED`: An on-chain transfer matching the expected amount has been observed; waiting for block confirmations. - `VERIFIED`: The matched transfer reached confirmation — the address is verified. - `EXPIRED`: Challenge was not matched within 180 minutes. - `DELETED`: Challenge was cancelled by the client. 
type SatoshiTestChallengeStatus string

// List of SatoshiTestChallengeStatus
const (
	SATOSHITESTCHALLENGESTATUS_PREPARE SatoshiTestChallengeStatus = "PREPARE"
	SATOSHITESTCHALLENGESTATUS_PENDING SatoshiTestChallengeStatus = "PENDING"
	SATOSHITESTCHALLENGESTATUS_MATCHED SatoshiTestChallengeStatus = "MATCHED"
	SATOSHITESTCHALLENGESTATUS_VERIFIED SatoshiTestChallengeStatus = "VERIFIED"
	SATOSHITESTCHALLENGESTATUS_EXPIRED SatoshiTestChallengeStatus = "EXPIRED"
	SATOSHITESTCHALLENGESTATUS_DELETED SatoshiTestChallengeStatus = "DELETED"
)

// All allowed values of SatoshiTestChallengeStatus enum
var AllowedSatoshiTestChallengeStatusEnumValues = []SatoshiTestChallengeStatus{
	"PREPARE",
	"PENDING",
	"MATCHED",
	"VERIFIED",
	"EXPIRED",
	"DELETED",
}

func (v *SatoshiTestChallengeStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SatoshiTestChallengeStatus(value)
	for _, existing := range AllowedSatoshiTestChallengeStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}
	*v = SatoshiTestChallengeStatus("unknown")
	return nil
}

// NewSatoshiTestChallengeStatusFromValue returns a pointer to a valid SatoshiTestChallengeStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSatoshiTestChallengeStatusFromValue(v string) (*SatoshiTestChallengeStatus, error) {
	ev := SatoshiTestChallengeStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SatoshiTestChallengeStatus: valid values are %v", v, AllowedSatoshiTestChallengeStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SatoshiTestChallengeStatus) IsValid() bool {
	for _, existing := range AllowedSatoshiTestChallengeStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SatoshiTestChallengeStatus value
func (v SatoshiTestChallengeStatus) Ptr() *SatoshiTestChallengeStatus {
	return &v
}

type NullableSatoshiTestChallengeStatus struct {
	value *SatoshiTestChallengeStatus
	isSet bool
}

func (v NullableSatoshiTestChallengeStatus) Get() *SatoshiTestChallengeStatus {
	return v.value
}

func (v *NullableSatoshiTestChallengeStatus) Set(val *SatoshiTestChallengeStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSatoshiTestChallengeStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSatoshiTestChallengeStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSatoshiTestChallengeStatus(val *SatoshiTestChallengeStatus) *NullableSatoshiTestChallengeStatus {
	return &NullableSatoshiTestChallengeStatus{value: val, isSet: true}
}

func (v NullableSatoshiTestChallengeStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSatoshiTestChallengeStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

