/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddressVerification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressVerification{}

// AddressVerification Summary of a self-custody address verification record. Returned as items in [List address verifications](#operation/list_address_verifications). Call [Get address verification](#operation/get_address_verification) with `verification_id` to retrieve method-specific provenance (`satoshi_test_detail` / `signature_detail`). 
type AddressVerification struct {
	// The unique identifier of this verification record.
	VerificationId string `json:"verification_id"`
	// The counterparty (self-custody) wallet address being verified.
	Address string `json:"address"`
	// The chain on which this address is verified.
	ChainId string `json:"chain_id"`
	Status AddressVerificationStatus `json:"status"`
	VerificationMethod AddressVerificationMethod `json:"verification_method"`
	// Timestamp (milliseconds) when verification completed. `null` while `status=PENDING` or `FAILED`.
	VerifiedAt NullableInt64 `json:"verified_at,omitempty"`
}

type _AddressVerification AddressVerification

// NewAddressVerification instantiates a new AddressVerification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressVerification(verificationId string, address string, chainId string, status AddressVerificationStatus, verificationMethod AddressVerificationMethod) *AddressVerification {
	this := AddressVerification{}
	this.VerificationId = verificationId
	this.Address = address
	this.ChainId = chainId
	this.Status = status
	this.VerificationMethod = verificationMethod
	return &this
}

// NewAddressVerificationWithDefaults instantiates a new AddressVerification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressVerificationWithDefaults() *AddressVerification {
	this := AddressVerification{}
	return &this
}

// GetVerificationId returns the VerificationId field value
func (o *AddressVerification) GetVerificationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationId
}

// GetVerificationIdOk returns a tuple with the VerificationId field value
// and a boolean to check if the value has been set.
func (o *AddressVerification) GetVerificationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationId, true
}

// SetVerificationId sets field value
func (o *AddressVerification) SetVerificationId(v string) {
	o.VerificationId = v
}

// GetAddress returns the Address field value
func (o *AddressVerification) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *AddressVerification) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *AddressVerification) SetAddress(v string) {
	o.Address = v
}

// GetChainId returns the ChainId field value
func (o *AddressVerification) GetChainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *AddressVerification) GetChainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *AddressVerification) SetChainId(v string) {
	o.ChainId = v
}

// GetStatus returns the Status field value
func (o *AddressVerification) GetStatus() AddressVerificationStatus {
	if o == nil {
		var ret AddressVerificationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AddressVerification) GetStatusOk() (*AddressVerificationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AddressVerification) SetStatus(v AddressVerificationStatus) {
	o.Status = v
}

// GetVerificationMethod returns the VerificationMethod field value
func (o *AddressVerification) GetVerificationMethod() AddressVerificationMethod {
	if o == nil {
		var ret AddressVerificationMethod
		return ret
	}

	return o.VerificationMethod
}

// GetVerificationMethodOk returns a tuple with the VerificationMethod field value
// and a boolean to check if the value has been set.
func (o *AddressVerification) GetVerificationMethodOk() (*AddressVerificationMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationMethod, true
}

// SetVerificationMethod sets field value
func (o *AddressVerification) SetVerificationMethod(v AddressVerificationMethod) {
	o.VerificationMethod = v
}

// GetVerifiedAt returns the VerifiedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressVerification) GetVerifiedAt() int64 {
	if o == nil || IsNil(o.VerifiedAt.Get()) {
		var ret int64
		return ret
	}
	return *o.VerifiedAt.Get()
}

// GetVerifiedAtOk returns a tuple with the VerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressVerification) GetVerifiedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.VerifiedAt.Get(), o.VerifiedAt.IsSet()
}

// HasVerifiedAt returns a boolean if a field has been set.
func (o *AddressVerification) HasVerifiedAt() bool {
	if o != nil && o.VerifiedAt.IsSet() {
		return true
	}

	return false
}

// SetVerifiedAt gets a reference to the given NullableInt64 and assigns it to the VerifiedAt field.
func (o *AddressVerification) SetVerifiedAt(v int64) {
	o.VerifiedAt.Set(&v)
}
// SetVerifiedAtNil sets the value for VerifiedAt to be an explicit nil
func (o *AddressVerification) SetVerifiedAtNil() {
	o.VerifiedAt.Set(nil)
}

// UnsetVerifiedAt ensures that no value is present for VerifiedAt, not even an explicit nil
func (o *AddressVerification) UnsetVerifiedAt() {
	o.VerifiedAt.Unset()
}

func (o AddressVerification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressVerification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["verification_id"] = o.VerificationId
	toSerialize["address"] = o.Address
	toSerialize["chain_id"] = o.ChainId
	toSerialize["status"] = o.Status
	toSerialize["verification_method"] = o.VerificationMethod
	if o.VerifiedAt.IsSet() {
		toSerialize["verified_at"] = o.VerifiedAt.Get()
	}
	return toSerialize, nil
}

func (o *AddressVerification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"verification_id",
		"address",
		"chain_id",
		"status",
		"verification_method",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddressVerification := _AddressVerification{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddressVerification)

	if err != nil {
		return err
	}

	*o = AddressVerification(varAddressVerification)

	return err
}

type NullableAddressVerification struct {
	value *AddressVerification
	isSet bool
}

func (v NullableAddressVerification) Get() *AddressVerification {
	return v.value
}

func (v *NullableAddressVerification) Set(val *AddressVerification) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressVerification) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressVerification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressVerification(val *AddressVerification) *NullableAddressVerification {
	return &NullableAddressVerification{value: val, isSet: true}
}

func (v NullableAddressVerification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressVerification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


