/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"fmt"
)

// SatoshiTestChallengeAction The action to perform when creating a Satoshi Test challenge. - `PREPARE`: Preview the verification address and amount. The 180-minute countdown is NOT started yet. Repeated `PREPARE` calls for the same `(chain_id, from_address)` refresh the amount. - `SUBMIT`: Activate the challenge and start the 180-minute countdown. If a `PREPARE` challenge already exists for this `(chain_id, from_address)` it is activated; otherwise a new challenge is created directly in `PENDING` state (one-shot flow). 
type SatoshiTestChallengeAction string

// List of SatoshiTestChallengeAction
const (
	SATOSHITESTCHALLENGEACTION_PREPARE SatoshiTestChallengeAction = "PREPARE"
	SATOSHITESTCHALLENGEACTION_SUBMIT SatoshiTestChallengeAction = "SUBMIT"
)

// All allowed values of SatoshiTestChallengeAction enum
var AllowedSatoshiTestChallengeActionEnumValues = []SatoshiTestChallengeAction{
	"PREPARE",
	"SUBMIT",
}

func (v *SatoshiTestChallengeAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SatoshiTestChallengeAction(value)
	for _, existing := range AllowedSatoshiTestChallengeActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}
	*v = SatoshiTestChallengeAction("unknown")
	return nil
}

// NewSatoshiTestChallengeActionFromValue returns a pointer to a valid SatoshiTestChallengeAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSatoshiTestChallengeActionFromValue(v string) (*SatoshiTestChallengeAction, error) {
	ev := SatoshiTestChallengeAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SatoshiTestChallengeAction: valid values are %v", v, AllowedSatoshiTestChallengeActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SatoshiTestChallengeAction) IsValid() bool {
	for _, existing := range AllowedSatoshiTestChallengeActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SatoshiTestChallengeAction value
func (v SatoshiTestChallengeAction) Ptr() *SatoshiTestChallengeAction {
	return &v
}

type NullableSatoshiTestChallengeAction struct {
	value *SatoshiTestChallengeAction
	isSet bool
}

func (v NullableSatoshiTestChallengeAction) Get() *SatoshiTestChallengeAction {
	return v.value
}

func (v *NullableSatoshiTestChallengeAction) Set(val *SatoshiTestChallengeAction) {
	v.value = val
	v.isSet = true
}

func (v NullableSatoshiTestChallengeAction) IsSet() bool {
	return v.isSet
}

func (v *NullableSatoshiTestChallengeAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSatoshiTestChallengeAction(val *SatoshiTestChallengeAction) *NullableSatoshiTestChallengeAction {
	return &NullableSatoshiTestChallengeAction{value: val, isSet: true}
}

func (v NullableSatoshiTestChallengeAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSatoshiTestChallengeAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

