/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddressVerificationDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressVerificationDetail{}

// AddressVerificationDetail Full detail of a single address verification record, including method-specific provenance.  - `verification_method=SIGNATURE` → `signature_detail` is populated, `satoshi_test_detail` is `null`. - `verification_method=SATOSHI_TEST` → `satoshi_test_detail` carries the latest challenge state (`status`, `remaining_seconds`, `matched_txid`); `signature_detail` is `null`. 
type AddressVerificationDetail struct {
	// The unique identifier of this verification record.
	VerificationId string `json:"verification_id"`
	// The counterparty (self-custody) wallet address being verified.
	Address string `json:"address"`
	// The chain on which this address is verified.
	ChainId string `json:"chain_id"`
	Status AddressVerificationStatus `json:"status"`
	VerificationMethod AddressVerificationMethod `json:"verification_method"`
	// Timestamp (milliseconds) when verification completed. `null` while `status=PENDING` or `FAILED`.
	VerifiedAt NullableInt64 `json:"verified_at,omitempty"`
	SatoshiTestDetail NullableAddressVerificationDetailSatoshiTestDetail `json:"satoshi_test_detail,omitempty"`
	SignatureDetail NullableAddressVerificationDetailSignatureDetail `json:"signature_detail,omitempty"`
}

type _AddressVerificationDetail AddressVerificationDetail

// NewAddressVerificationDetail instantiates a new AddressVerificationDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressVerificationDetail(verificationId string, address string, chainId string, status AddressVerificationStatus, verificationMethod AddressVerificationMethod) *AddressVerificationDetail {
	this := AddressVerificationDetail{}
	this.VerificationId = verificationId
	this.Address = address
	this.ChainId = chainId
	this.Status = status
	this.VerificationMethod = verificationMethod
	return &this
}

// NewAddressVerificationDetailWithDefaults instantiates a new AddressVerificationDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressVerificationDetailWithDefaults() *AddressVerificationDetail {
	this := AddressVerificationDetail{}
	return &this
}

// GetVerificationId returns the VerificationId field value
func (o *AddressVerificationDetail) GetVerificationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationId
}

// GetVerificationIdOk returns a tuple with the VerificationId field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetail) GetVerificationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationId, true
}

// SetVerificationId sets field value
func (o *AddressVerificationDetail) SetVerificationId(v string) {
	o.VerificationId = v
}

// GetAddress returns the Address field value
func (o *AddressVerificationDetail) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetail) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *AddressVerificationDetail) SetAddress(v string) {
	o.Address = v
}

// GetChainId returns the ChainId field value
func (o *AddressVerificationDetail) GetChainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetail) GetChainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *AddressVerificationDetail) SetChainId(v string) {
	o.ChainId = v
}

// GetStatus returns the Status field value
func (o *AddressVerificationDetail) GetStatus() AddressVerificationStatus {
	if o == nil {
		var ret AddressVerificationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetail) GetStatusOk() (*AddressVerificationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AddressVerificationDetail) SetStatus(v AddressVerificationStatus) {
	o.Status = v
}

// GetVerificationMethod returns the VerificationMethod field value
func (o *AddressVerificationDetail) GetVerificationMethod() AddressVerificationMethod {
	if o == nil {
		var ret AddressVerificationMethod
		return ret
	}

	return o.VerificationMethod
}

// GetVerificationMethodOk returns a tuple with the VerificationMethod field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetail) GetVerificationMethodOk() (*AddressVerificationMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationMethod, true
}

// SetVerificationMethod sets field value
func (o *AddressVerificationDetail) SetVerificationMethod(v AddressVerificationMethod) {
	o.VerificationMethod = v
}

// GetVerifiedAt returns the VerifiedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressVerificationDetail) GetVerifiedAt() int64 {
	if o == nil || IsNil(o.VerifiedAt.Get()) {
		var ret int64
		return ret
	}
	return *o.VerifiedAt.Get()
}

// GetVerifiedAtOk returns a tuple with the VerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressVerificationDetail) GetVerifiedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.VerifiedAt.Get(), o.VerifiedAt.IsSet()
}

// HasVerifiedAt returns a boolean if a field has been set.
func (o *AddressVerificationDetail) HasVerifiedAt() bool {
	if o != nil && o.VerifiedAt.IsSet() {
		return true
	}

	return false
}

// SetVerifiedAt gets a reference to the given NullableInt64 and assigns it to the VerifiedAt field.
func (o *AddressVerificationDetail) SetVerifiedAt(v int64) {
	o.VerifiedAt.Set(&v)
}
// SetVerifiedAtNil sets the value for VerifiedAt to be an explicit nil
func (o *AddressVerificationDetail) SetVerifiedAtNil() {
	o.VerifiedAt.Set(nil)
}

// UnsetVerifiedAt ensures that no value is present for VerifiedAt, not even an explicit nil
func (o *AddressVerificationDetail) UnsetVerifiedAt() {
	o.VerifiedAt.Unset()
}

// GetSatoshiTestDetail returns the SatoshiTestDetail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressVerificationDetail) GetSatoshiTestDetail() AddressVerificationDetailSatoshiTestDetail {
	if o == nil || IsNil(o.SatoshiTestDetail.Get()) {
		var ret AddressVerificationDetailSatoshiTestDetail
		return ret
	}
	return *o.SatoshiTestDetail.Get()
}

// GetSatoshiTestDetailOk returns a tuple with the SatoshiTestDetail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressVerificationDetail) GetSatoshiTestDetailOk() (*AddressVerificationDetailSatoshiTestDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.SatoshiTestDetail.Get(), o.SatoshiTestDetail.IsSet()
}

// HasSatoshiTestDetail returns a boolean if a field has been set.
func (o *AddressVerificationDetail) HasSatoshiTestDetail() bool {
	if o != nil && o.SatoshiTestDetail.IsSet() {
		return true
	}

	return false
}

// SetSatoshiTestDetail gets a reference to the given NullableAddressVerificationDetailSatoshiTestDetail and assigns it to the SatoshiTestDetail field.
func (o *AddressVerificationDetail) SetSatoshiTestDetail(v AddressVerificationDetailSatoshiTestDetail) {
	o.SatoshiTestDetail.Set(&v)
}
// SetSatoshiTestDetailNil sets the value for SatoshiTestDetail to be an explicit nil
func (o *AddressVerificationDetail) SetSatoshiTestDetailNil() {
	o.SatoshiTestDetail.Set(nil)
}

// UnsetSatoshiTestDetail ensures that no value is present for SatoshiTestDetail, not even an explicit nil
func (o *AddressVerificationDetail) UnsetSatoshiTestDetail() {
	o.SatoshiTestDetail.Unset()
}

// GetSignatureDetail returns the SignatureDetail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressVerificationDetail) GetSignatureDetail() AddressVerificationDetailSignatureDetail {
	if o == nil || IsNil(o.SignatureDetail.Get()) {
		var ret AddressVerificationDetailSignatureDetail
		return ret
	}
	return *o.SignatureDetail.Get()
}

// GetSignatureDetailOk returns a tuple with the SignatureDetail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressVerificationDetail) GetSignatureDetailOk() (*AddressVerificationDetailSignatureDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.SignatureDetail.Get(), o.SignatureDetail.IsSet()
}

// HasSignatureDetail returns a boolean if a field has been set.
func (o *AddressVerificationDetail) HasSignatureDetail() bool {
	if o != nil && o.SignatureDetail.IsSet() {
		return true
	}

	return false
}

// SetSignatureDetail gets a reference to the given NullableAddressVerificationDetailSignatureDetail and assigns it to the SignatureDetail field.
func (o *AddressVerificationDetail) SetSignatureDetail(v AddressVerificationDetailSignatureDetail) {
	o.SignatureDetail.Set(&v)
}
// SetSignatureDetailNil sets the value for SignatureDetail to be an explicit nil
func (o *AddressVerificationDetail) SetSignatureDetailNil() {
	o.SignatureDetail.Set(nil)
}

// UnsetSignatureDetail ensures that no value is present for SignatureDetail, not even an explicit nil
func (o *AddressVerificationDetail) UnsetSignatureDetail() {
	o.SignatureDetail.Unset()
}

func (o AddressVerificationDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressVerificationDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["verification_id"] = o.VerificationId
	toSerialize["address"] = o.Address
	toSerialize["chain_id"] = o.ChainId
	toSerialize["status"] = o.Status
	toSerialize["verification_method"] = o.VerificationMethod
	if o.VerifiedAt.IsSet() {
		toSerialize["verified_at"] = o.VerifiedAt.Get()
	}
	if o.SatoshiTestDetail.IsSet() {
		toSerialize["satoshi_test_detail"] = o.SatoshiTestDetail.Get()
	}
	if o.SignatureDetail.IsSet() {
		toSerialize["signature_detail"] = o.SignatureDetail.Get()
	}
	return toSerialize, nil
}

func (o *AddressVerificationDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"verification_id",
		"address",
		"chain_id",
		"status",
		"verification_method",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddressVerificationDetail := _AddressVerificationDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddressVerificationDetail)

	if err != nil {
		return err
	}

	*o = AddressVerificationDetail(varAddressVerificationDetail)

	return err
}

type NullableAddressVerificationDetail struct {
	value *AddressVerificationDetail
	isSet bool
}

func (v NullableAddressVerificationDetail) Get() *AddressVerificationDetail {
	return v.value
}

func (v *NullableAddressVerificationDetail) Set(val *AddressVerificationDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressVerificationDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressVerificationDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressVerificationDetail(val *AddressVerificationDetail) *NullableAddressVerificationDetail {
	return &NullableAddressVerificationDetail{value: val, isSet: true}
}

func (v NullableAddressVerificationDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressVerificationDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


