/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"fmt"
)

// AddressVerificationStatus The lifecycle status of an address verification record. - `PENDING`: A Satoshi Test challenge is in progress (countdown active or awaiting confirmation). - `VERIFIED`: The address ownership has been confirmed (by signature or by a matched Satoshi Test transfer). - `FAILED`: The verification attempt did not succeed (Satoshi Test expired without match, or signature verification rejected). 
type AddressVerificationStatus string

// List of AddressVerificationStatus
const (
	ADDRESSVERIFICATIONSTATUS_PENDING AddressVerificationStatus = "PENDING"
	ADDRESSVERIFICATIONSTATUS_VERIFIED AddressVerificationStatus = "VERIFIED"
	ADDRESSVERIFICATIONSTATUS_FAILED AddressVerificationStatus = "FAILED"
)

// All allowed values of AddressVerificationStatus enum
var AllowedAddressVerificationStatusEnumValues = []AddressVerificationStatus{
	"PENDING",
	"VERIFIED",
	"FAILED",
}

func (v *AddressVerificationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AddressVerificationStatus(value)
	for _, existing := range AllowedAddressVerificationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}
	*v = AddressVerificationStatus("unknown")
	return nil
}

// NewAddressVerificationStatusFromValue returns a pointer to a valid AddressVerificationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAddressVerificationStatusFromValue(v string) (*AddressVerificationStatus, error) {
	ev := AddressVerificationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AddressVerificationStatus: valid values are %v", v, AllowedAddressVerificationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AddressVerificationStatus) IsValid() bool {
	for _, existing := range AllowedAddressVerificationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AddressVerificationStatus value
func (v AddressVerificationStatus) Ptr() *AddressVerificationStatus {
	return &v
}

type NullableAddressVerificationStatus struct {
	value *AddressVerificationStatus
	isSet bool
}

func (v NullableAddressVerificationStatus) Get() *AddressVerificationStatus {
	return v.value
}

func (v *NullableAddressVerificationStatus) Set(val *AddressVerificationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressVerificationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressVerificationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressVerificationStatus(val *AddressVerificationStatus) *NullableAddressVerificationStatus {
	return &NullableAddressVerificationStatus{value: val, isSet: true}
}

func (v NullableAddressVerificationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressVerificationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

