/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"fmt"
)

// TravelRuleTransactionType The direction of the underlying transaction in a Travel Rule operation. - `DEPOSIT`: A deposit transaction (verifying the source address). - `WITHDRAW`: A withdrawal transaction (verifying the destination address). 
type TravelRuleTransactionType string

// List of TravelRuleTransactionType
const (
	TRAVELRULETRANSACTIONTYPE_DEPOSIT TravelRuleTransactionType = "DEPOSIT"
	TRAVELRULETRANSACTIONTYPE_WITHDRAW TravelRuleTransactionType = "WITHDRAW"
)

// All allowed values of TravelRuleTransactionType enum
var AllowedTravelRuleTransactionTypeEnumValues = []TravelRuleTransactionType{
	"DEPOSIT",
	"WITHDRAW",
}

func (v *TravelRuleTransactionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TravelRuleTransactionType(value)
	for _, existing := range AllowedTravelRuleTransactionTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}
	*v = TravelRuleTransactionType("unknown")
	return nil
}

// NewTravelRuleTransactionTypeFromValue returns a pointer to a valid TravelRuleTransactionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTravelRuleTransactionTypeFromValue(v string) (*TravelRuleTransactionType, error) {
	ev := TravelRuleTransactionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TravelRuleTransactionType: valid values are %v", v, AllowedTravelRuleTransactionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TravelRuleTransactionType) IsValid() bool {
	for _, existing := range AllowedTravelRuleTransactionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TravelRuleTransactionType value
func (v TravelRuleTransactionType) Ptr() *TravelRuleTransactionType {
	return &v
}

type NullableTravelRuleTransactionType struct {
	value *TravelRuleTransactionType
	isSet bool
}

func (v NullableTravelRuleTransactionType) Get() *TravelRuleTransactionType {
	return v.value
}

func (v *NullableTravelRuleTransactionType) Set(val *TravelRuleTransactionType) {
	v.value = val
	v.isSet = true
}

func (v NullableTravelRuleTransactionType) IsSet() bool {
	return v.isSet
}

func (v *NullableTravelRuleTransactionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTravelRuleTransactionType(val *TravelRuleTransactionType) *NullableTravelRuleTransactionType {
	return &NullableTravelRuleTransactionType{value: val, isSet: true}
}

func (v NullableTravelRuleTransactionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTravelRuleTransactionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

