/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
)

// checks if the ListBulkSends200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBulkSends200Response{}

// ListBulkSends200Response struct for ListBulkSends200Response
type ListBulkSends200Response struct {
	Data []PaymentBulkSend `json:"data,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// NewListBulkSends200Response instantiates a new ListBulkSends200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBulkSends200Response() *ListBulkSends200Response {
	this := ListBulkSends200Response{}
	return &this
}

// NewListBulkSends200ResponseWithDefaults instantiates a new ListBulkSends200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBulkSends200ResponseWithDefaults() *ListBulkSends200Response {
	this := ListBulkSends200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListBulkSends200Response) GetData() []PaymentBulkSend {
	if o == nil || IsNil(o.Data) {
		var ret []PaymentBulkSend
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBulkSends200Response) GetDataOk() ([]PaymentBulkSend, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListBulkSends200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []PaymentBulkSend and assigns it to the Data field.
func (o *ListBulkSends200Response) SetData(v []PaymentBulkSend) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListBulkSends200Response) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBulkSends200Response) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListBulkSends200Response) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *ListBulkSends200Response) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o ListBulkSends200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBulkSends200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableListBulkSends200Response struct {
	value *ListBulkSends200Response
	isSet bool
}

func (v NullableListBulkSends200Response) Get() *ListBulkSends200Response {
	return v.value
}

func (v *NullableListBulkSends200Response) Set(val *ListBulkSends200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListBulkSends200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListBulkSends200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBulkSends200Response(val *ListBulkSends200Response) *NullableListBulkSends200Response {
	return &NullableListBulkSends200Response{value: val, isSet: true}
}

func (v NullableListBulkSends200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBulkSends200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


