/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddressVerificationDetailSatoshiTestDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressVerificationDetailSatoshiTestDetail{}

// AddressVerificationDetailSatoshiTestDetail The latest Satoshi Test challenge associated with this verification. Present only when `verification_method=SATOSHI_TEST`. 
type AddressVerificationDetailSatoshiTestDetail struct {
	// The unique identifier of the Satoshi Test challenge.
	ChallengeId string `json:"challenge_id"`
	// The counterparty (self-custody) wallet address that must transfer the micro-deposit.
	FromAddress string `json:"from_address"`
	// The Cobo-generated verification address that will receive the micro-deposit.
	ToAddress string `json:"to_address"`
	// The exact amount (in the token's smallest unit) that must be transferred. The amount is unique per challenge and is used together with `to_address` to identify a matching on-chain transfer. 
	Amount string `json:"amount"`
	// The ID of the token used for the micro-deposit (typically the chain's native asset).
	TokenId string `json:"token_id"`
	// The chain on which the micro-deposit is expected.
	ChainId string `json:"chain_id"`
	Status SatoshiTestChallengeStatus `json:"status"`
	// Remaining time (in seconds) before the challenge expires. `0` when the challenge is not yet submitted or has already completed/expired. 
	RemainingSeconds int32 `json:"remaining_seconds"`
	// The on-chain transaction hash of the matching transfer, once matched.
	MatchedTxid NullableString `json:"matched_txid,omitempty"`
	// Timestamp (milliseconds) when the challenge was submitted and the countdown started.
	StartedAt NullableInt64 `json:"started_at,omitempty"`
	// Timestamp (milliseconds) when the challenge will expire if not matched.
	ExpiresAt NullableInt64 `json:"expires_at,omitempty"`
}

type _AddressVerificationDetailSatoshiTestDetail AddressVerificationDetailSatoshiTestDetail

// NewAddressVerificationDetailSatoshiTestDetail instantiates a new AddressVerificationDetailSatoshiTestDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressVerificationDetailSatoshiTestDetail(challengeId string, fromAddress string, toAddress string, amount string, tokenId string, chainId string, status SatoshiTestChallengeStatus, remainingSeconds int32) *AddressVerificationDetailSatoshiTestDetail {
	this := AddressVerificationDetailSatoshiTestDetail{}
	this.ChallengeId = challengeId
	this.FromAddress = fromAddress
	this.ToAddress = toAddress
	this.Amount = amount
	this.TokenId = tokenId
	this.ChainId = chainId
	this.Status = status
	this.RemainingSeconds = remainingSeconds
	return &this
}

// NewAddressVerificationDetailSatoshiTestDetailWithDefaults instantiates a new AddressVerificationDetailSatoshiTestDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressVerificationDetailSatoshiTestDetailWithDefaults() *AddressVerificationDetailSatoshiTestDetail {
	this := AddressVerificationDetailSatoshiTestDetail{}
	return &this
}

// GetChallengeId returns the ChallengeId field value
func (o *AddressVerificationDetailSatoshiTestDetail) GetChallengeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChallengeId
}

// GetChallengeIdOk returns a tuple with the ChallengeId field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetailSatoshiTestDetail) GetChallengeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChallengeId, true
}

// SetChallengeId sets field value
func (o *AddressVerificationDetailSatoshiTestDetail) SetChallengeId(v string) {
	o.ChallengeId = v
}

// GetFromAddress returns the FromAddress field value
func (o *AddressVerificationDetailSatoshiTestDetail) GetFromAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromAddress
}

// GetFromAddressOk returns a tuple with the FromAddress field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetailSatoshiTestDetail) GetFromAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromAddress, true
}

// SetFromAddress sets field value
func (o *AddressVerificationDetailSatoshiTestDetail) SetFromAddress(v string) {
	o.FromAddress = v
}

// GetToAddress returns the ToAddress field value
func (o *AddressVerificationDetailSatoshiTestDetail) GetToAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetailSatoshiTestDetail) GetToAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToAddress, true
}

// SetToAddress sets field value
func (o *AddressVerificationDetailSatoshiTestDetail) SetToAddress(v string) {
	o.ToAddress = v
}

// GetAmount returns the Amount field value
func (o *AddressVerificationDetailSatoshiTestDetail) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetailSatoshiTestDetail) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AddressVerificationDetailSatoshiTestDetail) SetAmount(v string) {
	o.Amount = v
}

// GetTokenId returns the TokenId field value
func (o *AddressVerificationDetailSatoshiTestDetail) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetailSatoshiTestDetail) GetTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *AddressVerificationDetailSatoshiTestDetail) SetTokenId(v string) {
	o.TokenId = v
}

// GetChainId returns the ChainId field value
func (o *AddressVerificationDetailSatoshiTestDetail) GetChainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetailSatoshiTestDetail) GetChainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *AddressVerificationDetailSatoshiTestDetail) SetChainId(v string) {
	o.ChainId = v
}

// GetStatus returns the Status field value
func (o *AddressVerificationDetailSatoshiTestDetail) GetStatus() SatoshiTestChallengeStatus {
	if o == nil {
		var ret SatoshiTestChallengeStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetailSatoshiTestDetail) GetStatusOk() (*SatoshiTestChallengeStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AddressVerificationDetailSatoshiTestDetail) SetStatus(v SatoshiTestChallengeStatus) {
	o.Status = v
}

// GetRemainingSeconds returns the RemainingSeconds field value
func (o *AddressVerificationDetailSatoshiTestDetail) GetRemainingSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RemainingSeconds
}

// GetRemainingSecondsOk returns a tuple with the RemainingSeconds field value
// and a boolean to check if the value has been set.
func (o *AddressVerificationDetailSatoshiTestDetail) GetRemainingSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemainingSeconds, true
}

// SetRemainingSeconds sets field value
func (o *AddressVerificationDetailSatoshiTestDetail) SetRemainingSeconds(v int32) {
	o.RemainingSeconds = v
}

// GetMatchedTxid returns the MatchedTxid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressVerificationDetailSatoshiTestDetail) GetMatchedTxid() string {
	if o == nil || IsNil(o.MatchedTxid.Get()) {
		var ret string
		return ret
	}
	return *o.MatchedTxid.Get()
}

// GetMatchedTxidOk returns a tuple with the MatchedTxid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressVerificationDetailSatoshiTestDetail) GetMatchedTxidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MatchedTxid.Get(), o.MatchedTxid.IsSet()
}

// HasMatchedTxid returns a boolean if a field has been set.
func (o *AddressVerificationDetailSatoshiTestDetail) HasMatchedTxid() bool {
	if o != nil && o.MatchedTxid.IsSet() {
		return true
	}

	return false
}

// SetMatchedTxid gets a reference to the given NullableString and assigns it to the MatchedTxid field.
func (o *AddressVerificationDetailSatoshiTestDetail) SetMatchedTxid(v string) {
	o.MatchedTxid.Set(&v)
}
// SetMatchedTxidNil sets the value for MatchedTxid to be an explicit nil
func (o *AddressVerificationDetailSatoshiTestDetail) SetMatchedTxidNil() {
	o.MatchedTxid.Set(nil)
}

// UnsetMatchedTxid ensures that no value is present for MatchedTxid, not even an explicit nil
func (o *AddressVerificationDetailSatoshiTestDetail) UnsetMatchedTxid() {
	o.MatchedTxid.Unset()
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressVerificationDetailSatoshiTestDetail) GetStartedAt() int64 {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret int64
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressVerificationDetailSatoshiTestDetail) GetStartedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *AddressVerificationDetailSatoshiTestDetail) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableInt64 and assigns it to the StartedAt field.
func (o *AddressVerificationDetailSatoshiTestDetail) SetStartedAt(v int64) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *AddressVerificationDetailSatoshiTestDetail) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *AddressVerificationDetailSatoshiTestDetail) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressVerificationDetailSatoshiTestDetail) GetExpiresAt() int64 {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret int64
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressVerificationDetailSatoshiTestDetail) GetExpiresAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *AddressVerificationDetailSatoshiTestDetail) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableInt64 and assigns it to the ExpiresAt field.
func (o *AddressVerificationDetailSatoshiTestDetail) SetExpiresAt(v int64) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *AddressVerificationDetailSatoshiTestDetail) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *AddressVerificationDetailSatoshiTestDetail) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

func (o AddressVerificationDetailSatoshiTestDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressVerificationDetailSatoshiTestDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["challenge_id"] = o.ChallengeId
	toSerialize["from_address"] = o.FromAddress
	toSerialize["to_address"] = o.ToAddress
	toSerialize["amount"] = o.Amount
	toSerialize["token_id"] = o.TokenId
	toSerialize["chain_id"] = o.ChainId
	toSerialize["status"] = o.Status
	toSerialize["remaining_seconds"] = o.RemainingSeconds
	if o.MatchedTxid.IsSet() {
		toSerialize["matched_txid"] = o.MatchedTxid.Get()
	}
	if o.StartedAt.IsSet() {
		toSerialize["started_at"] = o.StartedAt.Get()
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	return toSerialize, nil
}

func (o *AddressVerificationDetailSatoshiTestDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"challenge_id",
		"from_address",
		"to_address",
		"amount",
		"token_id",
		"chain_id",
		"status",
		"remaining_seconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddressVerificationDetailSatoshiTestDetail := _AddressVerificationDetailSatoshiTestDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddressVerificationDetailSatoshiTestDetail)

	if err != nil {
		return err
	}

	*o = AddressVerificationDetailSatoshiTestDetail(varAddressVerificationDetailSatoshiTestDetail)

	return err
}

type NullableAddressVerificationDetailSatoshiTestDetail struct {
	value *AddressVerificationDetailSatoshiTestDetail
	isSet bool
}

func (v NullableAddressVerificationDetailSatoshiTestDetail) Get() *AddressVerificationDetailSatoshiTestDetail {
	return v.value
}

func (v *NullableAddressVerificationDetailSatoshiTestDetail) Set(val *AddressVerificationDetailSatoshiTestDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressVerificationDetailSatoshiTestDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressVerificationDetailSatoshiTestDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressVerificationDetailSatoshiTestDetail(val *AddressVerificationDetailSatoshiTestDetail) *NullableAddressVerificationDetailSatoshiTestDetail {
	return &NullableAddressVerificationDetailSatoshiTestDetail{value: val, isSet: true}
}

func (v NullableAddressVerificationDetailSatoshiTestDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressVerificationDetailSatoshiTestDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


