/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"fmt"
)

// AddressVerificationMethod How a self-custody address was verified. - `SIGNATURE`: Verified by off-chain wallet signature (via `Get a self-custody signature challenge` + signed message). - `SATOSHI_TEST`: Verified by an on-chain micro-deposit (via Satoshi Test challenge). 
type AddressVerificationMethod string

// List of AddressVerificationMethod
const (
	ADDRESSVERIFICATIONMETHOD_SIGNATURE AddressVerificationMethod = "SIGNATURE"
	ADDRESSVERIFICATIONMETHOD_SATOSHI_TEST AddressVerificationMethod = "SATOSHI_TEST"
)

// All allowed values of AddressVerificationMethod enum
var AllowedAddressVerificationMethodEnumValues = []AddressVerificationMethod{
	"SIGNATURE",
	"SATOSHI_TEST",
}

func (v *AddressVerificationMethod) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AddressVerificationMethod(value)
	for _, existing := range AllowedAddressVerificationMethodEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}
	*v = AddressVerificationMethod("unknown")
	return nil
}

// NewAddressVerificationMethodFromValue returns a pointer to a valid AddressVerificationMethod
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAddressVerificationMethodFromValue(v string) (*AddressVerificationMethod, error) {
	ev := AddressVerificationMethod(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AddressVerificationMethod: valid values are %v", v, AllowedAddressVerificationMethodEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AddressVerificationMethod) IsValid() bool {
	for _, existing := range AllowedAddressVerificationMethodEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AddressVerificationMethod value
func (v AddressVerificationMethod) Ptr() *AddressVerificationMethod {
	return &v
}

type NullableAddressVerificationMethod struct {
	value *AddressVerificationMethod
	isSet bool
}

func (v NullableAddressVerificationMethod) Get() *AddressVerificationMethod {
	return v.value
}

func (v *NullableAddressVerificationMethod) Set(val *AddressVerificationMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressVerificationMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressVerificationMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressVerificationMethod(val *AddressVerificationMethod) *NullableAddressVerificationMethod {
	return &NullableAddressVerificationMethod{value: val, isSet: true}
}

func (v NullableAddressVerificationMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressVerificationMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

