/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListAddressVerifications200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAddressVerifications200Response{}

// ListAddressVerifications200Response Paginated list of address verification records.
type ListAddressVerifications200Response struct {
	// The page of address verification records.
	Data []AddressVerification `json:"data"`
	Pagination Pagination `json:"pagination"`
}

type _ListAddressVerifications200Response ListAddressVerifications200Response

// NewListAddressVerifications200Response instantiates a new ListAddressVerifications200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAddressVerifications200Response(data []AddressVerification, pagination Pagination) *ListAddressVerifications200Response {
	this := ListAddressVerifications200Response{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewListAddressVerifications200ResponseWithDefaults instantiates a new ListAddressVerifications200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAddressVerifications200ResponseWithDefaults() *ListAddressVerifications200Response {
	this := ListAddressVerifications200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ListAddressVerifications200Response) GetData() []AddressVerification {
	if o == nil {
		var ret []AddressVerification
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListAddressVerifications200Response) GetDataOk() ([]AddressVerification, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListAddressVerifications200Response) SetData(v []AddressVerification) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *ListAddressVerifications200Response) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *ListAddressVerifications200Response) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *ListAddressVerifications200Response) SetPagination(v Pagination) {
	o.Pagination = v
}

func (o ListAddressVerifications200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAddressVerifications200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *ListAddressVerifications200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAddressVerifications200Response := _ListAddressVerifications200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListAddressVerifications200Response)

	if err != nil {
		return err
	}

	*o = ListAddressVerifications200Response(varListAddressVerifications200Response)

	return err
}

type NullableListAddressVerifications200Response struct {
	value *ListAddressVerifications200Response
	isSet bool
}

func (v NullableListAddressVerifications200Response) Get() *ListAddressVerifications200Response {
	return v.value
}

func (v *NullableListAddressVerifications200Response) Set(val *ListAddressVerifications200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListAddressVerifications200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListAddressVerifications200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAddressVerifications200Response(val *ListAddressVerifications200Response) *NullableListAddressVerifications200Response {
	return &NullableListAddressVerifications200Response{value: val, isSet: true}
}

func (v NullableListAddressVerifications200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAddressVerifications200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


